#!/usr/bin/env python3

import sys, re, multiprocessing, os
import common

def compressdirectory(dir):    
    pngs = common.listfiles(dir, whitelist=[re.compile(r'(\.png$)')])
    jpgs = common.listfiles(dir, whitelist=[re.compile(r'(\.jpg$)')])    
    sem = multiprocessing.Semaphore(8)
    for png in pngs:
        sem.acquire()
        q = multiprocessing.Queue()
        p = multiprocessing.Process(target=compresspng, args=(q, sem, png))
        p.start()
    for jpg in jpgs:
        sem.acquire()        
        q = multiprocessing.Queue()
        p = multiprocessing.Process(target=compressjpeg, args=(q, sem, jpg))
        p.start()

def compresspng(q, sem, png):
    os.system("pngquant --ext .png --force --speed 3 " + png)
    sem.release()

def compressjpeg(q, sem, jpg):
    os.system("jpegtran -optimize -copy none -outfile " + jpg + " " + jpg)
    sem.release()

if __name__=="__main__":
    compressdirectory(sys.argv[1])